version: "3.8"
services:

	app:
		container_name: re-app
		build:
			context: .
			dockerfile: docker/Dockerfile
		restart: on-failure
		environment:
			- SERVICE_NAME=re-app
		ports:
			- "8080:8080"
		volumes:
			- ./:/app
		networks:
			- backend

networks:
	backend:
		driver: bridge
