version: "3.9"
services:
  app:
    container_name: re-test
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    environment:
      - SERVICE_NAME=re-test
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
