definitions:
  model.Order:
    properties:
      item:
        type: integer
      packets:
        additionalProperties:
          type: integer
        type: object
    type: object
info:
  contact: {}
paths:
  /orders/calculate:
    post:
      consumes:
      - application/json
      description: Get correct order items
      parameters:
      - description: items to calculate
        in: body
        minimum: 1
        name: items
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: Order Items
      tags:
      - order
      - items
      - calculate
  /packets/update:
    post:
      consumes:
      - application/json
      description: update available packs for order
      parameters:
      - description: name search by q
        format: email
        in: body
        name: items
        schema:
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: integer
            type: array
        "400":
          description: error
          schema:
            type: string
        "404":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: update packs
      tags:
      - order
      - items
      - update
swagger: "2.0"
